CREATE TABLE members
(
    id            BIGINT GENERATED By DEFAULT AS IDENTITY PRIMARY KEY,

    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname      VARCHAR(20)  NOT NULL,

    status        VARCHAR(20)  NOT NULL,
    role          VARCHAR(20)  NOT NULL,

    created_at    TIMESTAMPTZ  NOT NULL,
    updated_at    TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_members_email UNIQUE (email),

    CONSTRAINT ck_members_email_normalized
        CHECK (email = lower(btrim(email))),

    CONSTRAINT ck_members_nickname_length
        CHECK ( char_length(nickname) BETWEEN 2 AND 20),

    CONSTRAINT ck_members_status
        CHECK (
            status IN (
                       'PENDING',
                       'ACTIVE',
                       'RESTRICTED',
                       'SUSPENDED',
                       'WITHDRAWN',
                       'DELETED'
                )
            ),

    CONSTRAINT ck_members_role
        CHECK ( role IN ('USER', 'ADMIN'))
);

-- 중복값을 허용하지 않는 인덱스 생성
-- uk_members_nickname_lower : 생성할 인덱스의 이름
-- ON members : members 테이블에 적용
CREATE UNIQUE INDEX uk_members_nickname_lower
    ON members (lower(nickname));