CREATE TABLE member_agreements
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id     BIGINT      NOT NULL,
    terms_code    VARCHAR(32) NOT NULL,
    terms_version VARCHAR(50) NOT NULL,
    agreed_at     TIMESTAMPTZ NOT NULL,

--     존재하지 않는 회원의 동의 기록 저장 방지
    CONSTRAINT fk_member_agreements_member
        FOREIGN KEY (member_id)
            REFERENCES members (id)
            ON DELETE RESTRICT, -- 다른 테이블에서 참조하고 있는 행을 삭제하지 못하게 막는 외래키 옵션

--     같은 회원, 약관, 버전의 중복 저장 방지
    CONSTRAINT uk_member_agreements_member_terms_version
        UNIQUE (member_id, terms_code, terms_version),

--     정의되지 않은 약관 종류 저장 방지
    CONSTRAINT ck_member_agreements_terms_code
        CHECK (
            terms_code IN (
                           'SERVICE_TERMS',
                           'PRIVACY_COLLECTION_USE'
                )
            ),

--     빈 문자열이나 일반 공백만 있는 버전 저장 방지
    CONSTRAINT ck_member_agreements_terms_version
        CHECK (char_length(btrim(terms_version)) > 0)
);