CREATE TABLE email_verification_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    member_id   BIGINT      NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    revoked_at  TIMESTAMPTZ,

    version     BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_email_verification_tokens_member
        FOREIGN KEY (member_id)
            REFERENCES members (id)
            ON DELETE RESTRICT,

    CONSTRAINT uk_email_verification_tokens_hash
        UNIQUE (token_hash),

    CONSTRAINT ck_email_verification_tokens_hash
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),

    CONSTRAINT ck_email_verification_tokens_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT ck_email_verification_tokens_used_at
        CHECK (used_at IS NULL OR used_at >= created_at),

    CONSTRAINT ck_email_verification_tokens_revoked_at
        CHECK (revoked_at IS NULL OR revoked_at >= created_at),

    CONSTRAINT ck_email_verification_tokens_terminal_state
        CHECK (used_at IS NULL OR revoked_at IS NULL)
);

-- 회원별 토큰 조회, 폐기에 사용
CREATE INDEX idx_email_verification_tokens_member
    ON email_verification_tokens (member_id);